name = "item-analyzer"
main = "src/index.js"
compatibility_date = "2024-09-30"

[vars]
STRIPE_SECRET = ""
EBAY_TOKEN = ""
FACEBOOK_APP_ID = ""
MERCARI_API_KEY = ""
SENDGRID_API_KEY = ""
TWILIO_SID = ""
TWILIO_TOKEN = ""
TWILIO_FROM = ""
N8N_WEBHOOK_URL = ""
OPENSEARCH_NODE = "http://localhost:9200"
RABBITMQ_URL = "http://localhost:15672"
RABBITMQ_USER = "guest"
RABBITMQ_PASS = "guest"
# Add other API keys

# For KV
[[kv_namespaces]]
binding = "CACHE"
id = ""

# Supabase
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""

# For R2
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "item-images"

# AI Gateway
[ai]
binding = "AI"

# Observability
[observability]
enabled = true

# Security
[security]
enabled = true