name = "item-analyzer"
main = "src/index.js"
compatibility_date = "2024-09-30"

[vars]
STRIPE_SECRET = ""
EBAY_TOKEN = ""
FACEBOOK_APP_ID = ""
MERCARI_API_KEY = ""
SENDGRID_API_KEY = ""
TWILIO_SID = ""
TWILIO_TOKEN = ""
TWILIO_FROM = ""
# Add other API keys

# For D1
[[d1_databases]]
binding = "DB"
database_name = "item_analyzer_db"
database_id = ""

# For R2
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "item-images"

# AI Gateway
[ai]
binding = "AI"

# Observability
[observability]
enabled = true

# Security
[security]
enabled = true