name = "item-analyzer"
main = "src/index.js"
compatibility_date = "2024-09-30"

[vars]
STRIPE_SECRET = ""
EBAY_TOKEN = ""
FACEBOOK_APP_ID = ""
MERCARI_API_KEY = ""
SENDGRID_API_KEY = ""
# Add other API keys

# For D1
[[d1_databases]]
binding = "DB"
database_name = "item_analyzer_db"
database_id = ""

# AI Gateway
[ai]
binding = "AI"

# Observability
[observability]
enabled = true